import Head from 'next/head';
import styles from '../styles/Home.module.css';
import MuiNextLink from '@components/MuiNextLink';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Opinionated NextJs + MUI5 App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <MuiNextLink href="" target="_blank">Waterloo</MuiNextLink>!
        </h1>

        <p className={styles.description}>
          {`Contrary Capital's Waterloo Event Hub`}
        </p>
      </main>
    </div>
  )
}
